apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-publisher-f
  namespace: rabbit
  labels:
    app: rabbitmq-publisher
spec:
  selector:
    matchLabels:
      app: rabbitmq-publisher
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq-publisher
    spec:
      containers:
        - name: rabbitmq-publisher
          image: raihankhanraka/rabbit-publisher:0.4
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: RABBIT_HOST
              value: "rabbitmq-green.rabbit.svc.cluster.local"
            - name: RABBIT_VHOST
              value: "/"
            - name: RABBIT_PORT
              value: "5672"
            - name: RABBIT_QUEUE
              value: "queue-two"
            - name: RABBIT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-green-admin-cred
                  key: username
            - name: RABBIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-green-admin-cred
                  key: password
            - name: RABBIT_QUEUE_TYPE
              value: "quorum"
            - name: RABBIT_PUBLISH_INTERVAL
              value: "10"
            - name: MESSAGE_EACH_BATCH
              value: "10"
            - name: RAND_MSG_SIZE_IN_MB
              value: "1"
            - name: CLOSE_MSG_LOG
              value: "true"

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-publisher
  namespace: rabbit
  labels:
    app: rabbitmq-publisher
spec:
  clusterIP: None
  selector:
    app: rabbitmq-publisher
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80