apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-publisher
  namespace: rabbit
  labels:
    app: rabbitmq-publisher
spec:
  selector:
    matchLabels:
      app: rabbitmq-publisher
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq-publisher
    spec:
      containers:
        - name: rabbitmq-publisher
          image: raihankhanraka/rabbit-publisher:0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: RABBIT_HOST
              value: "fast-black-prawn.rmq6.cloudamqp.com"
            - name: RABBIT_VHOST
              value: "fiykjdln"
            - name: RABBIT_PORT
              value: "5672"
            - name: RABBIT_QUEUE
              value: "queue-one"
            - name: RABBIT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-remote-cred
                  key: username
            - name: RABBIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-remote-cred
                  key: password
            - name: RABBIT_QUEUE_TYPE
              value: "quorum"
            - name: RABBIT_PUBLISH_INTERVAL
              value: "5"
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-publisher
  namespace: rabbit
  labels:
    app: rabbitmq-publisher
spec:
  clusterIP: None
  selector:
    app: rabbitmq-publisher
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80